run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    #- deadcode
    #- depguard
    #- dogsled
    - dupl
    - errorlint
    - exportloopref
    #- exhaustive
    #- funlen
    #- gas
    #- gochecknoinits
    - goconst
    - gocognit
    - gocritic
    #- gocyclo
    #- gofmt
    #- goimports
    #- golint
    #- gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    #- interfacer
    #- lll
    #- maligned
    - megacheck
    #- misspell
    #- nakedret
    #- noctx
    #- nolintlint
    # - prealloc
    - revive
    #- rowserrcheck
    #- scopelint
    - staticcheck
    #- structcheck
    - stylecheck
    - typecheck
    - unconvert
    #- unparam
    - unused
    #- varcheck
    - whitespace
  fast: false

linters-settings:
  gosimple:
    checks: ["all", "-S1028"]
  staticcheck:
    checks: ["all"]
